[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  PNPM_FLAGS = "--no-frozen-lockfile"


[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/admin/index.html"
  status = 200
  conditions = {Query = {invite_token = ":token"}}

[[redirects]]
  from = "/*"
  to = "/admin/index.html"
  status = 200
  conditions = {Query = {recovery_token = ":token"}}
